// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'API Docs',
      items: [
        'apiDocs/list-all-messages.api',
        'apiDocs/list-mms-media',
        'apiDocs/plivo-message-api',
        'apiDocs/retrieve-message',
        'apiDocs/send-message',
      ],
    },
    {
      type: 'category',
      label: 'Quick Start',
      items: [
        'quickStart/goquickstart',
        'quickStart/javaQuickstart',
        'quickStart/node-expressjs',
        'quickStart/php',
        'quickStart/rubyquickstart',
      ],
    },
    {
      type: 'category',
      label: 'Voice API Docs',
      items: [
        'VoiceApiDocs/call',
        'VoiceApiDocs/conference',
        'VoiceApiDocs/plivo-message-api.info',
        'VoiceApiDocs/request',
        'VoiceApiDocs/response',
      ],
    },
    {
      type: 'category',
      label: 'Voice API Quick Start',
      items: [
        'voiceApiQuickstart/DotNETQuickstart',
        'voiceApiQuickstart/GoQuickstart',
        'voiceApiQuickstart/JavaQuickstart',
        'voiceApiQuickstart/NodejsQuickstart',
        'voiceApiQuickstart/PHPQuickstart',
        'voiceApiQuickstart/RubyQuickstart',
      ],
    },
  ],
};

export default sidebars;
// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   apiDocsSidebar: require('./sidebars/apiSidebar').default,
//   voiceApiSidebar: require('./sidebars/voiceSidebar').default,
// };

// export default sidebars;
